code/config/routes.rb
Code::Application.routes.draw do
  get "timesheet/new"

  get "adminhome/index"
  post "adminhome/search"

  get "userhome/index"

  get "requests/admin_index"
  get "timesheet/show"

  resources :manageusers
  resources :requests
  
  resources :timesheets

  match 'users/sign_up' => redirect('/404.html')

  match "/requests/:id" => "requests#update"
      
  devise_for :users

  root :to=> 'userhome#index'  

end

code/app/controllers/manageusers_controller.rb
class ManageusersController < AdminController

  before_filter :check_for_cancel, :only => [:create, :update]
  def check_for_cancel
    if params[:commit] == "Cancel"
      redirect_to manageusers_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

 def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def create
    Rails.logger=Logger.new(STDOUT)
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to manageusers_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @request }
      else
        logger.info('Error creating the user')
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #TODO: check for deactivated user
    @user = User.find(params[:id])
    ui_user = params[:user]
    if ui_user[:password].nil? || ui_user[:password].empty?
      ui_user.delete(:password)
    end
    ui_user.delete(:password_confirmation)
    #calling update_attributes for validation checks
    if @user.update_attributes(ui_user)
      redirect_to manageusers_path
    else
    #TODO: show error messages
      render 'edit'
    end
  end

  def index
    @users = User.where("is_user_active = ?", true).order(:last_name)
  end

  def destroy
    @user = User.find(params[:id])
    @user.is_user_active = false
    @user.save

    redirect_to manageusers_path
  end
end

code/app/views/manageusers/_form.html.erb
<% if @user.errors.any? %>
<div id="error_explanation" class="error">
	<h2><%= pluralize(@user.errors.count, "error") %> prohibited this request from being saved:</h2>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>

		<li>
			<%= msg %>
		</li>

		<% end %>
	</ul>
</div>
<% end %>

<table align="center">
	<tr>
		<div class="field" >
			<td><%= f.label :name, "Last Name" %><span class="req"> *</span></td>
			<td><%= f.text_field :last_name, autofocus: true %></td>
		</div>
	</tr>
	<tr>
		<div class="field" >
			<td><%= f.label :name, "First Name" %><span class="req"> *</span></td>
			<td><%= f.text_field :name, autofocus: true %></td>
		</div>
	</tr>
	<tr>
		<div class="field" >
			<td><%= f.label :address %></td>
			<td><%= f.text_field :address, autofocus: true %></td>
		</div>
	</tr>
	<tr>
		<div class="field" >
			<td><%= f.label :phone %><span class="req"> *</span></td>
			<td><%= f.text_field :phone, autofocus: true %></td>
		</div>
	</tr>
	<tr>
		<div class="field" >
			<td><%= f.label :email %><span class="req"> *</span></td>
			<td><%= f.email_field :email, autofocus: true %></td>
		</div>
	</tr>
	<tr>
		<div class="field" >
			<td><%= f.label :password %>
			<% if @validatable %> <em>(<%= @minimum_password_length %> characters minimum)</em> <% end %> <span class="req"> *</span></td>
			<td><%= f.password_field :password, autocomplete: "off" %></td>
		</div>
	</tr>
	<% if buttonText == 'Save'%>
	<tr>
		<td>(Leave blank if you don't want
		<br/>
		to update the password.)</td>
		<td></td>
		</div>
	</tr>
	<% end%>

	<tr>
		<div class="field" >
			<td><%= f.label(:password_confirmation, "Password Confirmation ") %><span class="req"> *</span></td>
			<td><%= f.password_field :password_confirmation, autocomplete: "off" %></td>
		</div>
	</tr>
	<tr>
		<div class="field" >
			<td><%= f.label(:is_admin, "Is Employee Admin?") %></td>
			<td><%= f.check_box :is_admin %></td>
		</div>
	</tr>
	<tr>
		<div class="field" >
			<td><%= f.label(:allowOutsideLogin, "Allow Outside Login") %></td>
			<td><%= f.check_box :allowOutsideLogin %></td>
		</div>
	</tr>
	<tr>
		<div class="field" >
			<td><%= f.label(:exempt, "Exempt Employee") %></td>
			<td><%= f.check_box :exempt %></td>
		</div>
	</tr>
	<tr>
		<td></td><td></td>
	</tr>
	<tr>
		<td></td><td></td>
	</tr>
	<tr>
		<td></td><td></td>
	</tr>
	<tr>
		<div class="actions" align="center">
			<td align="right"><%= f.submit buttonText %></td>
			<td><%= f.submit 'Cancel'%></td>
	</tr>
	</div>
</table>

code/app/views/manageusers/edit.html.erb
<center>
	<h2>Edit Employee details</h2>
</center>

<%= form_for :user, url: manageuser_path(@user), method: :put do |f| %>
<%= render partial: "form", locals: {f: f, buttonText: 'Save'} %>
<% end %>

code/app/views/manageusers/index.html.erb
<h1>Listing Employees</h1>
<div>
	<%= link_to "Create New Employee", action: "new" %>
	<br>
	<br>
</div>
<table id="table-fields" align="center">
	<tr>
		<th>Last Name</th>
		<th>First Name</th>
		<th>Email</th>
		<th>Phone</th>
		<th>Employee Type</th>
		<th>Address</th>
		<th>Exempted Employee</th>
		<th>Outside Login Allowed</th>
		<th></th>
	</tr>
	<%
 count = 0
%>
	<% @users.each do |user| %>
	<% trClass = ""
    if count%2 == 1
      trClass = "alt"
    end
    count = count + 1
%>
	<tr class="<%= trClass%>">
		<td><%= link_to user.last_name, edit_manageuser_path(user) %></td>
		<td><%= user.name%></td>
		<td><%= user.email %></td>
		<td><%= user.phone %></td>
		<td><% if user.is_admin %>
		Admin
		<%
		else %>Normal<%

		end  %></td>
		<td><%= user.address %></td>
		<td><%= user.exempt %></td>
		<td><%= user.allowOutsideLogin %></td>
		<td><%= link_to "Delete", manageuser_path(user), method: :delete, data: { confirm: 'Are you sure?' }%></td>
	</tr>
	<% end %>
</table>

code/app/views/manageusers/new.html.erb
<center>
	<h2>New Employee Setup</h2>
</center>

<%= form_for :user, url:manageusers_path do |f| %>

<%= render partial: "form", locals: {f: f, buttonText: 'Create'} %>
<% end %>