code/config/routes.rb
Code::Application.routes.draw do
  get "timesheet/new"

  get "adminhome/index"
  post "adminhome/search"

  get "userhome/index"

  get "requests/admin_index"
  get "timesheet/show"

  resources :manageusers
  resources :requests
  
  resources :timesheets

  match 'users/sign_up' => redirect('/404.html')

  match "/requests/:id" => "requests#update"
      
  devise_for :users

  root :to=> 'userhome#index'  

end

code/app/models/request.rb
class Request < ActiveRecord::Base
  default_scope :order=> 'created_at DESC'
  belongs_to :user
  attr_accessible :comment, :end, :start, :minutes, :request_type, :date, :status, :created_at
  
  STATUS_DROP = {"pending" => 0, "approved" => 1, "rejected" => 2}
  TYPE_DROP = { "regular" => 0, "sick leave" => 1, "holiday leave" => 2, "other" => 3 }
end

code/app/controllers/requests_controller.rb
class RequestsController < SecureController
  # GET /requests
  # GET /requests.json
  def admin_index
	 
	 @requests = Request.where(status: 0).order("requests.created_at DESC")
	 respond_to do |format|
	 format.html # admin_index.html.erb
         format.json { render json: @requests}
	end
  end

  def index
    is_admin = current_user.is_admin
    
    if is_admin
      redirect_to :action=>'admin_index'
    else
      @requests = Request.where(user_id: current_user.id).order("requests.created_at DESC")
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
      end
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])
    @request.user = current_user
    respond_to do |format|
    @time1 = @request.start
    @time2 = @request.end
    @request.minutes = TimeDifference.between(@time1, @time2).in_minutes
    @request.created_at=Time.now
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    Rails.logger=Logger.new(STDOUT)

    
    respond_to do |format|
    @request = Request.find(params[:id])
      
    if @request.update_attributes(params[:request])
      @request.update_attribute(:minutes, TimeDifference.between(@request.start, @request.end).in_minutes)
      if @request.status==1
        
        logger.info "timesheet updated"
        Timesheet.create(date: @request.date, clockin: @request.start, clockout: @request.end,minutes: @request.minutes, user: @request.user,request_type: @request.request_type, flag: 1)
        
      end

      is_admin = current_user.is_admin
      if is_admin 
	if @request.status==0
	  format.html { redirect_to :back, notice: 'Request Updated' }  
	else   
	  logger.info "inside notice"
          format.html { redirect_to @request, notice: 'Request Updated' }  
	end     
      else
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      end

    else
      is_admin = current_user.is_admin
      if is_admin
        Rails.logger.info(@request.errors.messages.inspect)
        format.html { render action: "admin_index" }
        format.json { render json: @request.errors, status: :unprocessable_entity }

      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end 
    end
    
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
end

code/app/helpers/requests_helper.rb
module RequestsHelper
end

code/app/views/requests/_form.html.erb
<%= form_for @request, :html => {:class => 'app-form'} do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation" class="error">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>
  
  <div>
    <%= f.label :type %>
    <%= select("request","request_type", Request::TYPE_DROP, {include_blank: false}) %>
  </div>
  
  <div>
    <%= f.label :start %>
    <%= f.time_select :start %>
  </div>
  
  <div>
    <%= f.label :end %>
    <%= f.time_select :end %>
  </div>
  
  <div class="app-text-area">
    <%= f.label :comment %>
    <%= f.text_area :comment, :cols => 40, :rows => 10 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

code/app/views/requests/admin_index.html.erb
<h1>Listing Requests</h1>

<table id="table-fields" align="center">
	<tr>
		<th>Employee Name </th>
		<th>Date </th>
		<th>Start time</th>
		<th>End time </th>
		<th>Time (in Hours)</th>
		<th>Type</th>
		<th>Note</th>
		<th>Status</th>
		<th></th>
	</tr>

	<%
 count = 0
%>
	<% @requests.each do |request| %>
	<% trClass = ""
    if count%2 == 1
      trClass = "alt"
    end
    count = count + 1
%>
	<tr class="<%= trClass%>">
		<td><%= request.user.name %></td>
		<td><%= request.date %></td>
		<td><%= request.start.strftime("%H:%M:%S") %></td>
		<td><%= request.end.strftime("%H:%M:%S") %></td>
		<td><%= Timesheet.getMinutesInHours(request.minutes) %></td>
		<td><%= Request::TYPE_DROP.index(request.request_type) %></td>
		<td><%= request.comment%></td>
		<%=form_for request do |f| %>
		<td><%= select("request", "status" , Request::STATUS_DROP, :selected=>f.object.status) %></td>
		<td><%= f.submit %></td>
		<%end%>

		<!--<td><%=button_to "submit", {:action=>'update',:controller=>'requests',:id=>request} ,:method=>:put %></td>-->

	</tr>

	<% end %>

</table>

code/app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

code/app/views/requests/index.html.erb
<h1>Listing Requests</h1>
<div>
	<%= link_to 'Create new request', new_request_path %>
	<br />
	<br />
</div>

<table id="table-fields">
	<tr>
		<th>Employee Name</th>		
		<th>Date</th>
		<th>Start time</th>
		<th>End time</th>
		<th>Time (in Hours)</th>
		<th>Type</th>
		<th>Status</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<%
 count = 0
%>
	<% @requests.each do |request| %>
	<% trClass = ""
    if count%2 == 1
      trClass = "alt"
    end
    count = count + 1
%>

	<tr class="<%= trClass%>">
		<td><%= request.user.name %></td>		
		<td><%= request.date %></td>
		<td><%= request.start.strftime("%H:%M:%S") %></td>
		<td><%= request.end.strftime("%H:%M:%S") %></td>
		<td><%= Timesheet.getMinutesInHours(request.minutes) %></td>		
		<td><%= Request::TYPE_DROP.index(request.request_type) %></td>
		<td><%= Request::STATUS_DROP.index(request.status)%></td>
		<!--<td><%= request.status %></td>-->
		<td><%= link_to 'Show', request %></td>
		
		<td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td><% if request.status==0 %>
			<%= link_to 'Edit', edit_request_path(request) %>
		<%end%></td>
	</tr>
	<% end %>
</table>

<br />

code/app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

code/app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>