code/config/routes.rb
Code::Application.routes.draw do
  get "timesheet/new"

  get "adminhome/index"
  post "adminhome/search"

  get "userhome/index"

  get "requests/admin_index"
  get "timesheet/show"

  resources :manageusers
  resources :requests
  
  resources :timesheets

  match 'users/sign_up' => redirect('/404.html')

  match "/requests/:id" => "requests#update"
      
  devise_for :users

  root :to=> 'userhome#index'  

end

code/app/controllers/userhome_controller.rb
class UserhomeController < SecureController
  def index
    if current_user.is_admin == true
      redirect_to :controller=>'adminhome', :action => 'index' and return
    end
    if params[:start_period] != nil && params[:end_period] != nil
      start_period = params[:start_period];
      end_period = params[:end_period];
      @start_period = start_period.to_date
      @end_period = end_period.to_date
  
    else
      start_period = Date.today
      end_period = Date.today  
      period = Timesheet.get_period(start_period, end_period, Date.today)
      @start_period = period[0]
      @end_period = period[1]
  
    end    
    @timesheets = current_user.timesheets.where("date >= ? AND date <= ?", @start_period, @end_period)
  end
end

code/app/helpers/userhome_helper.rb
module UserhomeHelper
end

code/app/views/userhome/index.html.erb
<% content_for :javascript_includes do %>
<%= javascript_include_tag "usrhome.js" %>
<% end %>

<h1>Welcome <%= current_user.name%>!</h1>
<h2 class="day center">Current time:</h2>
<div class="clockContainer center">
	<h2 class="clock-box center"><span id="current_time" class="clock"> <%= Time.now.strftime("%k:%M:%S")%></span></h2>
	<h3 class="day center"><%= Time.now.strftime("%A %d %b")%></h3>
</div>

<% clockin_status = !current_user.timesheets.last || current_user.timesheets.last.clockout? || current_user.timesheets.last.date < Date.today %>
<% clockout_status = current_user.timesheets.last && !current_user.timesheets.last.clockout? && current_user.timesheets.last.date == Date.today %>

<%= form_for :timesheet, url: timesheets_path do |f|%>
<p align="center">
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.hidden_field :request_type, { "regular" => 0, "sick leave" => 1, "holiday leave" => 2, "other" => 3}%>
	<%if clockin_status == true%>
	<%= f.submit "Clock-In", :class => "alizarin-flat-button"%>
	<%end%>
	<%if clockout_status == true%>
	<%= f.submit "Clock-Out", :class => "alizarin-flat-button"%>
	<%end%>
	<br/>
	
	<div>
		<center><span style="font-size:18px; font-weight: bold; margin-right:15px;">Timesheet from <%= @start_period.strftime("%m/%d/%y")%> to <%= @end_period.strftime("%m/%d/%y")%></span></center>
	</div>
	<div>
		<span style="float: left; font-weight: bold"><%= link_to "Previous timesheet", {:controller=>'userhome', :action=>'index', :start_period=> @start_period.to_date - 15.days, :end_period => @end_period.to_date - 15.days } %></span>
		<span style="float: right;font-weight: bold"><%= link_to "Next timesheet", {:controller=>'userhome', :action=>'index', :start_period=> @start_period.to_date + 15.days, :end_period => @end_period.to_date + 15.days } %></span>
	</div>
</p>
<% end %>

<% month = Date.today.month%>
<% year = Date.today.year%>

<br/>
<table id="table-fields" align="center">
	<tr>
		<th>Date</th>
		<th>Clock In</th>
		<th>Clock Out</th>
		<th>Time (in Hours)</th>
		<th>Type</th>
		<th></th>
	</tr>
	<% count = 0%>
	<% @timesheets.each do |t|%>
	<% trClass = ""
    if count%2 == 1
      trClass = "alt"
    end
    count = count + 1
%>
	<tr class="<%= trClass%>">
		<td><%= t.date.strftime("%A %d %b %Y") %></td>
		<td><%= t.clockin.strftime("%H:%M") %></td>
		<%if t.clockout == nil%>
		<td><%= t.clockout%> </td>
		<%else%>
		<td><%= t.clockout.strftime("%H:%M") %></td>
		<%end%>
		<td><%= t.getMinutesInHours %></td>
		<% if 0 == t.request_type%>
		<td>Regular</td>
		<%elsif 1 == t.request_type%>
		<td>Sick Leave </td>
		<%elsif 2 == t.request_type%>
		<td>Holiday Leave </td>
		<%else %>
		<td>Other</td>
		<%end%>
		<% if t.flag==1%>
		<td>Request</td>
		<%else%>
		<td></td>
		<%end%>
	</tr>
	<% end %>
</table>